services:
  - type: web
    name: energize-stockist-form
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
